### ISSUE TITLE
Feature request - Multiple Boss Bar

### ISSUE THREAD

**Issue by BrotherSharper** [theripper93/Boss-Bar#1]
Allow the user to set multiple HP bars hidden beneath the current boss bar for usage with Paragon Monsters.

**Comment by theripper93** [comment]
You can currently have multiple bars, i'm not sure what you mean with multiple hp bar, usually when you have a multy phase battle you just switch creature, could you elaborate for me please?

**Comment by BrotherSharper** [comment]
> 
> 
> You can currently have multiple bars, i'm not sure what you mean with multiple hp bar, usually when you have a multy phase battle you just switch creature, could you elaborate for me please?

Yeah I currently just switch the creature or just change the HP accordingly. But it would be more dramatic if there was another bar hidden beneath the currently dropping Boss bar.
For example, the first bar is Red, then beneath it is a second one with a blue color, and finally the dark background when that second bar also starts to deplete (similar to the health of some fighting games).
Perhaps it could be made to queue up multiple creatures or set a number of times that the target creature regains HP when it goes to zero (to define a second phase within the same token)

**Comment by theripper93** [comment]
The idea is cool but it's a lot of work to avoid switching a token haha :) - and i have 2 more modules coming up soon lol

**Comment by BrotherSharper** [comment]
Hey, no problem!
If you think it is too much work then please close this issue, just throwing out ideas at random lol
