### ISSUE TITLE
[BUG] Width gets messed up with Minimal UI module

### ISSUE THREAD

**Issue by EsotericOdyssey** [theripper93/Boss-Bar#10]
![image](https://user-images.githubusercontent.com/78229350/139532223-4878d687-07e6-4311-82ef-32f5b68f9612.png)
tested it, works fine with minimal UI turned off, but it'd be nice if I could have Minimal UI on without the bar going under the collapsed right sidebar

**Comment by theripper93** [comment]
i'm afraid i cannot account for every module that changes core CSS, that said it's possible that with the changes that will be required with v9 this issue will be fixed then (since in core v9 this same issue happens)
