### ISSUE TITLE
[Request] Bar features

### ISSUE THREAD

**Issue by B14d3r11** [theripper93/Boss-Bar#11]
So... I am evil, lets just start with that.

First I would like to request the ability to apply multiple HP bars to the screen targeting different attributes. Most of my bosses are assholes and have multiple HP bars or barriers

Second, if the multiple bars is a thing that can be done, can it be added so that the Foreground/Background Image can be selected per bar? 

Idk if it is possible to have a variable number of bars so just setting a maximum of like five would be good.

**Comment by theripper93** [comment]
No multiple bars sorry. You can customize the bars per token (there is a macro in the compendium) so you could have multiple actors to represent the different health bars
