### ISSUE TITLE
Feature request: One boss bar for multiple npc

### ISSUE THREAD

**Issue by BlackWand1** [theripper93/Boss-Bar#13]
Hey!

Would it be possible to get one boss bar for all selected tokens, where the bar would be the total of all HP.

So if I would select 20x npc with 100 HP each, there would be one boss bar with 2000 "hp".
Right now - there is one boss bar for each selected token.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
