### ISSUE TITLE
feature request: option to invert values for bar

### ISSUE THREAD

**Issue by EsotericOdyssey** [theripper93/Boss-Bar#14]
Bar Brawl has a feature where you can "invert" a bar's values, which makes 0 of a given resource look like a full bar, and it ticks down each time anything is added. This works nicely for systems where rather than subtracting "HP", damage is represented by adding "wounds" to a character. It'd be nice if Boss Bar had a similar feature.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
