### ISSUE TITLE
in pf2 the boss bar over extends into the effects hud

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [theripper93/Boss-Bar#18]
![image](https://github.com/theripper93/Boss-Bar/assets/62528192/c86832df-5109-4c2a-872e-32105a250357)

it just needs to be shrunk down width wise within the pf2 system.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
