### ISSUE TITLE
Feature Request - Demon Lord Compatible

### ISSUE THREAD

**Issue by AetherianRPG** [theripper93/Boss-Bar#2]
Is it possible to make this module compatible with Shadow of the Demon Lord system?

**Comment by theripper93** [comment]
Could you be more specific on why it is not compatible? I don’t know every game system unfortunately

**Comment by AetherianRPG** [comment]
In demonlord characters and creatures do not have health points that are subtracted when they take damage. Instead, they have a health total and add damage points. When damage reaches health value, the character or creature begins to die. So when you look at a creature's token in demonlord, the token bar marks damage and not health and starts at 0 and goes up to maximum health.

**Comment by theripper93** [comment]
what's the problem? just have the boss bar start at 0 and go up

**Comment by AetherianRPG** [comment]
Yeah, I know. I was just wondering if it could go down just like default instead of going up. But forget about it. Thank you very much for your time and patiente. And keep up the good work. Love your modules.

**Comment by theripper93** [comment]
no worries it just would be kinda hard to make it work with everything, just gotta work with what you got :P
