### ISSUE TITLE
One Enhancement Suggestion - Sub-Bar (SWADE)

### ISSUE THREAD

**Issue by tech097** [theripper93/Boss-Bar#20]
I play Savage Worlds Adventure Edition (SWADE) on Foundry and this would be a great way to build intrigue for the boss. However, the system doesn't use HP to track health, instead it counts how many Wounds out of a Set Number of Maximum Wounds a character has. ~~That's why it looks weird when the enemy gets damaged but the bar grows more red.~~

~~Would it be possible to add a way to change the colors of the bar so that the color that shrinks is red? Whether it's simply adding a new color picker option for the background bar or an invert colors option it'd be very helpful.~~

Also, SWADE also takes into account levels of Fatigue out of a Set Number of Maximum Fatigue when calculating wounds. For that reason would it be possible to add an extra sub-bar to place underneath the main bar?

Not mandatory by any means at all I just think this would be a neat thing to include in my sessions, it just isn't 100% doable without these changes is all.

EDIT: I just realized that I could change the bars and invert them myself, I didn't realize it was possible because it wouldn't load when I tried doing it, but closing and re-opening the boss bar reloaded it and showed it was possible, apologies!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
