### ISSUE TITLE
Offset?

### ISSUE THREAD

**Issue by MastaGooz** [theripper93/Boss-Bar#21]
Hi ! 
Is there a way to set some x/y offset for the boss bar (maybe i'm missing it, but I looked everywhere)?
That would be super cool to prevent the bar from overlaping with UI stuff like the carousel combat tracker :)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
