### ISSUE TITLE
Boss bar leaves unnecessary gap with some Carousel Combat Tracker settings

### ISSUE THREAD

**Issue by jagoe** [theripper93/Boss-Bar#22]
Hey there,
I'm using both modules mentioned in the title, but I use the Combat Carousel at the bottom of my viewport. The new behavior introduced in v1.2.0 (Bossbar will now offset itself to accomodate Carousel Combat Tracker) leads to a huge gap unless I display the Boss Bar at the bottom as well (which I don't want).
Could you make the new behavior dependent on a client setting so I can turn it off?

Here's a screenshot that doesn't demonstrate my actual setup, but demonstrates the problem:
![image](https://github.com/theripper93/Boss-Bar/assets/2989750/50ef9913-a717-4161-82d5-e778c454a83c)

I'm happy to answer any questions or test a solution before you release it.

Thanks in advance,
J

**Comment by theripper93** [comment]
That is the old Combat Carousel. Not my Carousel Combat Tracker

**Comment by jagoe** [comment]
Oh, sorry. I wasn't even aware that the old one had been discontinued. Thanks for the clarification!
