### ISSUE TITLE
Boss Bar appears on top of Effects, blocking text fields.

### ISSUE THREAD

**Issue by TheTenk** [theripper93/Boss-Bar#23]
I can't speak for if it happens in other systems, but in Pathfinder 2nd Edition the boss bar will cover up text windows and effects on the right side next to the chat. Is it possible to make the bar be underneath/behind the effects row, or have customizable width?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

Note that boss bar cannot take account of every system custom interface or theme that is not inserted in the core layout. I recommend looking at the custom css module or moving the bar to the bottom .
