### ISSUE TITLE
When trying to place Boss Bar at bottom of screen, doesn't appear

### ISSUE THREAD

**Issue by dogstarrb** [theripper93/Boss-Bar#24]
The Boss Bar works fine when I leave it on the default, but my group much prefers the bar to go along the bottom. The bar does not appear and several errors appear in the console. Even with all other modules disabled, errors are still appearing.
![image](https://github.com/theripper93/Boss-Bar/assets/7331744/29993fbb-31f7-455f-b445-ef171145ecf8)
![image](https://github.com/theripper93/Boss-Bar/assets/7331744/60098d6e-ee5c-4aaf-9472-697ae535782f)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
