### ISSUE TITLE
Feature suggestion: Temporary Hit Points

### ISSUE THREAD

**Issue by msalafia** [theripper93/Boss-Bar#25]
As the title, what do youthink about adding another blue bar on top of the existing one showing temporary hit points?. Something like the default token bar of Foundry.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
