### ISSUE TITLE
Bug: Bar doesn't work in none DnD System.

### ISSUE THREAD

**Issue by Vendare** [theripper93/Boss-Bar#4]
Gamesystem : Age of Sigmar - Soulbound
Current HP Path : combat.health.toughness.value
Total HP Path : combat.health.toughness.max
Other Modules Running : None

The Bar doesn't move it stays completely filled no matter what the health pool is set to.

**Comment by theripper93** [comment]
i'm pretty sure the path is setup wrong but i have no clue where the correct path would be

**Comment by Vendare** [comment]
The System uses weird paths the value is correct. The same path is used for the Combat Numbers Module and it works.

**Comment by theripper93** [comment]
so is it in actor.data.combat.health.toughness.value ?

**Comment by Vendare** [comment]
seems to be a path issue then its actor.data.data.combat.health.toughness.value.
Your module doesn't expect the second data

**Comment by theripper93** [comment]
Current HP Path : data.combat.health.toughness.value
Total HP Path : data.combat.health.toughness.max

should work
I left the extra data out on purpuse in case a system doesen't use the data.data
