### ISSUE TITLE
[BUG] Boss bar not updating properly with LANCER system.

### ISSUE THREAD

**Issue by yoshisman8** [theripper93/Boss-Bar#5]
When utilizing the Lancer system, the health bar is not updating properly, only updating sporadically under unknown criteria. 
I'm utilizing Boss-Bar v0.7.6 with Foundry v0.8.7 and Lancer v0.9.5.

**Comment by theripper93** [comment]
does the health system work differently in lancer?

**Comment by yoshisman8** [comment]
Nope, it uses a single variable to store health under `data.derived.current_hp` I set up the field and it just wont update properly

**Comment by theripper93** [comment]
unfortunatelly boss bar won't work with system that don't use the classic max hp\ current hp system. Sorry but no compatibility is planned :(
