### ISSUE TITLE
Feature request: Frame for the Boss Bar

### ISSUE THREAD

**Issue by BlackWand1** [theripper93/Boss-Bar#7]
Ability to add a frame for the boss bar, a simple picture. Pretty much like this.
![image](https://user-images.githubusercontent.com/85252943/131260243-b6757f56-2b50-430b-9803-3d3b0c525b12.png)

Would also be cool of the Boss tokens image would be a picture to the left/right of the bar.

**Comment by theripper93** [comment]
There are no plans on adding such features , as they will cause issues with scaling and look weird in generalized cases as the bar is not static

**Comment by BlackWand1** [comment]
The token picture to the left of the bar only then?
